### ISSUE TITLE
Versioning routes

### ISSUE THREAD

**Issue by davidianbonner** [guiwoda/route-binder#3]
Route versioning may be a useful feature, it would make working with an API with multiple versions (differing routes) simpler. 

Going to fork and have a look at the best way to achieve this.

Cheers

**Comment by guiwoda** [comment]
@dbonner1987 great!

I think [dingo does it](https://github.com/dingo/api/wiki/Creating-API-Endpoints), so if you go with their Router extension, you should be covered.

I'm not sure, but we should be dingo-compatible, as their RoutingServiceProvider just rebinds the router in the IoC. As long as our RouteBinderServiceProvider is booted after theirs, we should be OK.

**Comment by guiwoda** [comment]
@dbonner1987 I'll close this issue, let us know if you ever revisit this! Hopefully with a PR ;-)

Cheers!

**Comment by davidianbonner** [comment]
@guiwoda of course.

I've currently made a handful of changes to cater to our needs, including route arguments and grouping.

My only concern at the moment is the performance. I suspect route caching will resolve this though.

Cheers
